AWSTemplateFormatVersion: "2010-09-09"
Description: "golang serverless attempt."
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  VaultToken:
    Type: "String"


Globals:
  Function:
    Handler: "main"
    Timeout: 10
    Runtime: "go1.x"

Resources:
  createDevice:
      Type: "AWS::Serverless::Function"
      Properties:
        CodeUri: "cmd/createDevice"
        Environment:
          Variables:
            RUNNING_ENVIRONMENT: "Local"
            TABLE_NAME: "Devices"
        Events:
          ApiEvent:
            Type: "HttpApi"
          Api:
            Type: "Api"
            Properties:
              Path: "/api/devices"
              Method: "post"
  # getDevice:
  #     Type: "AWS::Serverless::Function"
  #     Properties:
  #       CodeUri: "cmd/device"
  #       Environment:
  #         Variables:
  #           RUNNING_ENVIRONMENT: "Local"
  #           TABLE_NAME: "Devices"
  #       Events:
  #         ApiEvent:
  #           Type: "HttpApi"
  #         Api:
  #           Type: "Api"
  #           Properties:
  #             Path: "/api/devices/{id}"
  #             Method: "get"